"""Reduce the committed benchmark runs to the figures a landing page may quote (R119).

The rule R119 exists to enforce: a number on the front page is recomputed from
run records, or it is not shown. So this reads `benchmark/results/**/runs.jsonl`
and writes `docs/benchmark.json`; where there are no run records it writes an
**absence with a reason**, and the page prints the reason rather than a number.

That is not a hypothetical branch. As of 5 October 2026 `benchmark/results/`
holds a `.gitkeep` and nothing else, while `docs/research/tables.md` carries
figures — 0.8387 correct over n=31 — generated from a run on somebody's machine
that was never committed. Those figures may well be right, and nobody can check
them from this repository, which is exactly the difference between a result and
a claim. Committing the run records fills this in; until then the landing page
says the benchmark has no committed evidence, which is true and is the more
useful thing to say.

    python scripts/benchmarkfigures.py [--check]
"""

from __future__ import annotations

import argparse
import io
import json
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout = io.TextIOWrapper(
        sys.stdout.buffer, encoding="utf-8", errors="replace", line_buffering=True
    )

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "benchmark" / "results"
OUT = ROOT / "docs" / "benchmark.json"

NO_RECORDS = (
    "no run records are committed under benchmark/results, so nothing here can "
    "be recomputed — docs/research/tables.md was generated from a run that was "
    "not kept"
)


def runs() -> list[dict]:
    found: list[dict] = []
    for path in sorted(RESULTS.rglob("runs.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                found.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return found


def figures() -> dict:
    records = runs()
    if not records:
        return {"absent": NO_RECORDS}

    by_arm: dict[str, list[dict]] = {}
    for record in records:
        by_arm.setdefault(str(record.get("arm", "unknown")), []).append(record)

    arms = {}
    for arm, rows in sorted(by_arm.items()):
        graded = [r for r in rows if r.get("correct") is not None]
        if not graded:
            arms[arm] = {"n": 0, "absent": "no graded scenario in these records"}
            continue
        arms[arm] = {
            "n": len(graded),
            "correct": round(sum(1 for r in graded if r["correct"]) / len(graded), 4),
        }
    return {
        "from": "benchmark/results/**/runs.jsonl",
        "runs": len(records),
        "arms": arms,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    payload = {
        "note": (
            "Generated by scripts/benchmarkfigures.py from the committed run "
            "records. Do not edit by hand: a benchmark figure that was typed is "
            "indistinguishable from one that was measured."
        ),
        "benchmark": figures(),
    }
    rendered = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print("FAIL  docs/benchmark.json is stale — run python scripts/benchmarkfigures.py")
            return 1
        print("docs/benchmark.json is current")
        return 0

    OUT.write_text(rendered, encoding="utf-8")
    absent = payload["benchmark"].get("absent")
    print(f"wrote docs/benchmark.json — {'absent: ' + absent if absent else payload['benchmark']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
