"""Capture the press screenshots from the running site (R109).

The media kit shows the console, and the only honest way to do that is to
photograph it — so this drives a real browser over real URLs and writes both
the images and a manifest saying, per image, which URL it came from, at what
width, when, and at which commit. The page renders the manifest, so every
caption is a fact about the capture rather than a label somebody typed.

Regenerated by one command when the site changes, the way `buildbrand.py`
regenerates the icons. A screenshot that silently ages is worse than none: a
journalist writing from a year-old picture of a page that has moved on is
describing something that no longer exists.

**The mark is deliberately not among the assets.** A media kit exists so that
someone can republish, and [docs/BRAND.md](../docs/BRAND.md) records that the
artwork's origin and licensing have not been established — "resolve before any
public launch, not after". Offering it for download would be distributing an
image nobody has rights to, to exactly the people most likely to publish it.
Screenshots are different: they are this project's own interface.

    python scripts/buildpress.py [--site http://localhost:3011]
"""

from __future__ import annotations

import argparse
import io
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

from playwright.sync_api import sync_playwright

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout = io.TextIOWrapper(
        sys.stdout.buffer, encoding="utf-8", errors="replace", line_buffering=True
    )

ROOT = Path(__file__).resolve().parents[1]
IMAGES = ROOT / "apps" / "web" / "public" / "press"
MANIFEST = ROOT / "apps" / "web" / "lib" / "press.generated.json"

WIDTH = 1440
HEIGHT = 900

SHOTS = [
    ("landing", "/", "The claim, and four numbers a reader can go and recount"),
    (
        "incident",
        "/incidents/INC-2026-0903",
        "One incident: the causal chain, each step mapped to a technique and citing the records behind it",
    ),
    ("attack", "/attack", "What the incident library has observed, tactic by tactic"),
    ("observatory", "/observatory", "Live threat intelligence, grouped by indicator and defanged"),
    ("actions", "/actions", "Every action, its risk, its rollback and who must authorise it"),
]


def commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return "unknown"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", default="http://localhost:3011")
    parser.add_argument("--out", default=str(IMAGES))
    args = parser.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    sha = commit()
    captured: list[dict[str, str | int]] = []

    with sync_playwright() as play:
        browser = play.chromium.launch()
        page = browser.new_context(
            viewport={"width": WIDTH, "height": HEIGHT}, device_scale_factor=2
        ).new_page()
        for name, route, caption in SHOTS:
            url = args.site + route
            response = page.goto(url, wait_until="networkidle")
            if response is None or response.status >= 400:
                print(f"FAIL  {route} answered {response.status if response else 'nothing'}")
                browser.close()
                return 1
            # Fonts before pixels: `display: swap` paints a fallback first, and
            # a screenshot taken then shows a typeface the site does not use.
            page.evaluate("() => document.fonts && document.fonts.ready")
            page.wait_for_timeout(400)
            target = out / f"{name}.png"
            page.screenshot(path=str(target))
            captured.append(
                {
                    "name": name,
                    "file": f"/press/{name}.png",
                    "route": route,
                    "url": url,
                    "caption": caption,
                    "width": WIDTH,
                    "height": HEIGHT,
                    "bytes": target.stat().st_size,
                }
            )
            print(f"  {route:34} -> {target.name}  ({target.stat().st_size // 1024} kB)")
        browser.close()

    MANIFEST.write_text(
        json.dumps(
            {
                "note": (
                    "Generated by scripts/buildpress.py. Every entry records the "
                    "URL the image was captured from; the page prints it, so a "
                    "caption cannot drift from what was photographed."
                ),
                "captured_at": datetime.now(UTC).isoformat(),
                "commit": sha,
                "site": args.site,
                "shots": captured,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"\nwrote {MANIFEST.relative_to(ROOT)} — {len(captured)} shots at {sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
