"""Generate the citation block on the site from `CITATION.cff`.

R108's rule, the same as R57's for the stack list: the BibTeX and APA a reader
copies must come from the one file GitHub renders as "Cite this repository",
not from a string typed into a component. A citation retyped by hand is right
on the day it is typed and drifts afterwards — a new version, a moved URL, a
DOI that finally exists — and the drift is invisible until somebody cites the
stale one.

The DOI is not in the file until Zenodo mints one. Until then the block says
"no DOI yet" rather than carrying a placeholder that looks like a DOI; when it
exists, add `doi:` to `CITATION.cff` and re-run this.

Run after changing `CITATION.cff`:

    python scripts/buildcitation.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CFF = ROOT / "CITATION.cff"
OUT = ROOT / "apps" / "web" / "lib" / "citation.generated.json"


def bibtex_key(cff: dict) -> str:
    family = cff["authors"][0]["family-names"].lower()
    year = str(cff["date-released"])[:4]
    return f"{family}{year}pashupatastra"


def render(cff: dict) -> dict:
    authors = [f"{a['family-names']}, {a['given-names']}" for a in cff["authors"]]
    apa_authors = ", ".join(
        f"{a['family-names']}, {a['given-names'][0]}." for a in cff["authors"]
    )
    released = str(cff["date-released"])
    year, month = released[:4], str(int(released[5:7]))
    doi = cff.get("doi")
    version = cff.get("version")

    lines = [
        f"@software{{{bibtex_key(cff)},",
        f"  author = {{{' and '.join(authors)}}},",
        f"  title = {{{cff['title']}}},",
        f"  year = {{{year}}},",
        f"  month = {{{month}}},",
    ]
    if version:
        lines.append(f"  version = {{{version}}},")
    if doi:
        lines.append(f"  doi = {{{doi}}},")
    lines.append(f"  url = {{{cff['url']}}},")
    lines.append("}")

    apa = f"{apa_authors} ({year}). {cff['title']}"
    if version:
        apa += f" (Version {version})"
    apa += " [Computer software]. "
    apa += f"https://doi.org/{doi}" if doi else cff["url"]

    return {
        "note": "Generated by scripts/buildcitation.py from CITATION.cff. Do not edit by hand.",
        "title": cff["title"],
        "authors": authors,
        "year": year,
        "version": version,
        "date_released": released,
        "url": cff["url"],
        "repository": cff.get("repository-code"),
        "doi": doi,
        "bibtex": "\n".join(lines),
        "apa": apa,
    }


def main() -> int:
    cff = yaml.safe_load(CFF.read_text(encoding="utf-8"))
    rendered = render(cff)
    OUT.write_text(json.dumps(rendered, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(rendered["bibtex"])
    print(rendered["apa"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
