"""Derive the site's brand assets from the source artwork.

Sources, which are the files to edit — never the derivatives:

    apps/web/public/logo.png                   the lockup: wordmark + spear
    apps/web/public/Pashupatastra icon 1.webp  the spear alone, square

Derivatives, all regenerated by this script:

    apps/web/public/logo.webp   the header lockup
    apps/web/app/icon.png       browser tab and search
    apps/web/app/apple-icon.png home-screen icon

Three transformations, each for a reason the site makes visible.

**The white outline comes off.** The lockup is drawn with a heavy white halo —
52% of its opaque pixels are near-white — which is what you want on a light
page and exactly wrong on this one, where it reads as a sticker cut from a
magazine. Keying on "is this pixel whitish" would also remove the white flame
and the silver ferrules, which are part of the drawing, so the halo is found by
where it *is* rather than what colour it is: the coloured core is grown by a
couple of pixels to keep its anti-aliased edge, and alpha is clipped to that.
Interior whites survive because they sit inside the core.

**The transparent margin comes off.** `logo.png` is a 1172px square whose
artwork occupies a 3:1 band across the middle. Shipping the margin costs 400 KB
on every page load to render nothing.

**The icon is a PNG.** Next's App Router reads `icon.(ico|jpg|jpeg|png|svg)`
and silently ignores anything else — a `.webp` there produces no `<link>` at
all and the browser falls back to its default globe.

Usage:  python scripts/buildbrand.py
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageChops, ImageFilter

WEB = Path(__file__).resolve().parents[1] / "apps" / "web"

LOCKUP_SOURCE = WEB / "public" / "logo.png"
SPEAR_SOURCE = WEB / "public" / "Pashupatastra icon 1.webp"

LOCKUP_OUT = WEB / "public" / "logo.webp"
ICON_OUT = WEB / "app" / "icon.png"
APPLE_ICON_OUT = WEB / "app" / "apple-icon.png"
FAVICON_ICO = WEB / "public" / "favicon.ico"
"""In `public/`, not `app/`. Next emits its own `<link>` for `app/favicon.ico`
*in addition to* anything `metadata.icons` declares, and its version claims
`sizes="16x16"` for a file that also holds 32 and 48 — telling a browser the
larger bitmaps are not there. Serving it as a static file leaves one accurate
declaration."""
FAVICON_48 = WEB / "public" / "favicon-48x48.png"
FAVICON_96 = WEB / "public" / "favicon-96x96.png"

ICO_SIZES = [(16, 16), (32, 32), (48, 48)]
"""A .ico carries several bitmaps. Browsers that ignore the PNG link still find
this one, and 48 is what Google Search asks for as a minimum."""

ICON_SIZE = 512
APPLE_ICON_SIZE = 180
"""180 is Apple's expected size. The tab icon is generated larger and left for
the browser to scale, since Next declares one file for every size."""

SATURATION_FLOOR = 0.28
"""Above this a pixel is coloured enough to be ink rather than halo."""

DARK_CEILING = 170
"""Below this a pixel is dark enough to be ink whatever its saturation — the
spear's shadows are neither colourful nor white."""

GROW = 5
"""MaxFilter kernel. Wide enough to keep the artwork's anti-aliased edge, narrow
enough not to drag the halo back in with it."""


def trim(image: Image.Image) -> Image.Image:
    box = image.getchannel("A").getbbox()
    return image.crop(box) if box else image


def dehalo(image: Image.Image) -> Image.Image:
    """Clip alpha to the coloured core, grown slightly."""
    image = trim(image.convert("RGBA"))
    width, height = image.size
    pixels = image.load()

    core = Image.new("L", (width, height), 0)
    core_pixels = core.load()
    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            if a < 40:
                continue
            highest, lowest = max(r, g, b), min(r, g, b)
            saturation = 0.0 if highest == 0 else (highest - lowest) / highest
            if saturation > SATURATION_FLOOR or highest < DARK_CEILING:
                core_pixels[x, y] = 255

    grown = core.filter(ImageFilter.MaxFilter(GROW)).filter(ImageFilter.GaussianBlur(1.2))
    result = image.copy()
    result.putalpha(ImageChops.multiply(image.getchannel("A"), grown))
    return trim(result)


def square(image: Image.Image) -> Image.Image:
    """Centre the artwork on a square canvas.

    The spear is drawn corner to corner precisely because a diagonal is the
    longest line a square holds — at 32px that is the difference between a
    recognisable weapon and a smudge. Padding to square preserves that.
    """
    image = trim(image.convert("RGBA"))
    width, height = image.size
    side = max(width, height)
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(image, ((side - width) // 2, (side - height) // 2))
    return canvas


def main() -> int:
    lockup = dehalo(Image.open(LOCKUP_SOURCE))
    lockup.save(LOCKUP_OUT, "WEBP", quality=92, method=6, exact=True)
    print(f"{LOCKUP_OUT.name:18} {lockup.size[0]}x{lockup.size[1]}  "
          f"{LOCKUP_OUT.stat().st_size // 1024} KB "
          f"(from {LOCKUP_SOURCE.stat().st_size // 1024} KB)")

    spear = square(Image.open(SPEAR_SOURCE))
    spear.resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS).save(ICON_OUT, "PNG", optimize=True)
    spear.resize((APPLE_ICON_SIZE, APPLE_ICON_SIZE), Image.LANCZOS).save(
        APPLE_ICON_OUT, "PNG", optimize=True
    )
    print(f"{ICON_OUT.name:18} {ICON_SIZE}x{ICON_SIZE}")
    print(f"{APPLE_ICON_OUT.name:18} {APPLE_ICON_SIZE}x{APPLE_ICON_SIZE}")

    # Google Search reads a square favicon of at least 48px from a stable URL.
    # These are the sizes it and older browsers actually look for.
    spear.resize((48, 48), Image.LANCZOS).save(FAVICON_48, "PNG", optimize=True)
    spear.resize((96, 96), Image.LANCZOS).save(FAVICON_96, "PNG", optimize=True)
    spear.resize((256, 256), Image.LANCZOS).save(FAVICON_ICO, "ICO", sizes=ICO_SIZES)
    print(f"{FAVICON_48.name:18} 48x48")
    print(f"{FAVICON_96.name:18} 96x96")
    print(f"{FAVICON_ICO.name:18} {', '.join(f'{w}x{h}' for w, h in ICO_SIZES)}")

    # No favicon.svg. The artwork is raster, and wrapping a PNG in an <svg>
    # gives none of the reasons to prefer one — it does not scale, it is not
    # smaller, and it is not editable. A real one needs the vector redraw
    # docs/ROADMAP.md already records as owed.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
