"""Derive the site's brand assets from the source artwork.

Sources, which are the files to edit — never the derivatives:

    apps/web/public/logo.png                   the lockup: wordmark + spear
    apps/web/public/Pashupatastra icon 1.webp  the spear alone, square

Derivatives, all regenerated by this script:

    apps/web/public/logo.webp   the header lockup
    apps/web/app/icon.png       browser tab and search
    apps/web/app/apple-icon.png home-screen icon

Three transformations, each for a reason the site makes visible.

**The white outline comes off.** The lockup is drawn with a heavy white halo —
52% of its opaque pixels are near-white — which is what you want on a light
page and exactly wrong on this one, where it reads as a sticker cut from a
magazine. Keying on "is this pixel whitish" would also remove the white flame
and the silver ferrules, which are part of the drawing, so the halo is found by
where it *is* rather than what colour it is: the coloured core is grown by a
couple of pixels to keep its anti-aliased edge, and alpha is clipped to that.
Interior whites survive because they sit inside the core.

**The transparent margin comes off.** `logo.png` is a 1172px square whose
artwork occupies a 3:1 band across the middle. Shipping the margin costs 400 KB
on every page load to render nothing.

**The icon is a PNG.** Next's App Router reads `icon.(ico|jpg|jpeg|png|svg)`
and silently ignores anything else — a `.webp` there produces no `<link>` at
all and the browser falls back to its default globe.

Usage:  python scripts/buildbrand.py
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

WEB = Path(__file__).resolve().parents[1] / "apps" / "web"

LOCKUP_SOURCE = WEB / "public" / "logo.png"
SPEAR_SOURCE = WEB / "public" / "Pashupatastra icon 1.webp"

LOCKUP_OUT = WEB / "public" / "logo.webp"
ICON_OUT = WEB / "app" / "icon.png"
APPLE_ICON_OUT = WEB / "app" / "apple-icon.png"
FAVICON_ICO = WEB / "public" / "favicon.ico"
"""In `public/`, not `app/`. Next emits its own `<link>` for `app/favicon.ico`
*in addition to* anything `metadata.icons` declares, and its version claims
`sizes="16x16"` for a file that also holds 32 and 48 — telling a browser the
larger bitmaps are not there. Serving it as a static file leaves one accurate
declaration."""
FAVICON_48 = WEB / "public" / "favicon-48x48.png"
FAVICON_96 = WEB / "public" / "favicon-96x96.png"

OG_OUT = WEB / "public" / "og.png"
OG_SIZE = (1200, 630)
"""What every link preview crops to. Smaller and it is upscaled; a different
ratio and the sides are cut."""

GROUND = (11, 13, 17)
"""`--ground` in the dark palette — the card should look like the page it opens."""

TAGLINE = "Observe. Reason. Act. Verify."

FONT_CANDIDATES = (
    "Inter-Regular.ttf",
    "C:/Windows/Fonts/segoeui.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
)
"""The card is a committed artifact, so a font only has to exist on the machine
that regenerates it. The wordmark itself comes from the artwork rather than
from type, so a substitution here changes one line of small text and nothing
that carries the brand."""

ICO_SIZES = [(16, 16), (32, 32), (48, 48)]
"""A .ico carries several bitmaps. Browsers that ignore the PNG link still find
this one, and 48 is what Google Search asks for as a minimum."""

ICON_SIZE = 512
APPLE_ICON_SIZE = 180
"""180 is Apple's expected size. The tab icon is generated larger and left for
the browser to scale, since Next declares one file for every size."""

SATURATION_FLOOR = 0.28
"""Above this a pixel is coloured enough to be ink rather than halo."""

DARK_CEILING = 170
"""Below this a pixel is dark enough to be ink whatever its saturation — the
spear's shadows are neither colourful nor white."""

GROW = 5
"""MaxFilter kernel. Wide enough to keep the artwork's anti-aliased edge, narrow
enough not to drag the halo back in with it."""


def trim(image: Image.Image) -> Image.Image:
    box = image.getchannel("A").getbbox()
    return image.crop(box) if box else image


def dehalo(image: Image.Image) -> Image.Image:
    """Clip alpha to the coloured core, grown slightly."""
    image = trim(image.convert("RGBA"))
    width, height = image.size
    pixels = image.load()

    core = Image.new("L", (width, height), 0)
    core_pixels = core.load()
    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            if a < 40:
                continue
            highest, lowest = max(r, g, b), min(r, g, b)
            saturation = 0.0 if highest == 0 else (highest - lowest) / highest
            if saturation > SATURATION_FLOOR or highest < DARK_CEILING:
                core_pixels[x, y] = 255

    grown = core.filter(ImageFilter.MaxFilter(GROW)).filter(ImageFilter.GaussianBlur(1.2))
    result = image.copy()
    result.putalpha(ImageChops.multiply(image.getchannel("A"), grown))
    return trim(result)


def square(image: Image.Image) -> Image.Image:
    """Centre the artwork on a square canvas.

    The spear is drawn corner to corner precisely because a diagonal is the
    longest line a square holds — at 32px that is the difference between a
    recognisable weapon and a smudge. Padding to square preserves that.
    """
    image = trim(image.convert("RGBA"))
    width, height = image.size
    side = max(width, height)
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(image, ((side - width) // 2, (side - height) // 2))
    return canvas


def load_font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for candidate in FONT_CANDIDATES:
        try:
            return ImageFont.truetype(candidate, size)
        except OSError:
            continue
    return ImageFont.load_default()


def social_card(lockup: Image.Image) -> Image.Image:
    """The 1200x630 image a link preview shows.

    Built from the lockup rather than re-typeset, so the name on the card is the
    same artwork as the name in the header.
    """
    card = Image.new("RGB", OG_SIZE, GROUND)
    draw = ImageDraw.Draw(card)

    # Every position below is derived from the artwork's own height. Hardcoding
    # them put the tagline through the middle of the spear.
    width = 720
    height = round(width * lockup.size[1] / lockup.size[0])
    art = lockup.resize((width, height), Image.LANCZOS)

    block = height + 34 + 30 + 30 + 3          # art, gap, text, gap, rule
    top = (OG_SIZE[1] - block) // 2
    card.paste(art, ((OG_SIZE[0] - width) // 2, top), art)

    font = load_font(30)
    box = draw.textbbox((0, 0), TAGLINE, font=font)
    text_y = top + height + 34
    draw.text(
        ((OG_SIZE[0] - (box[2] - box[0])) // 2, text_y),
        TAGLINE,
        font=font,
        fill=(141, 151, 166),          # --muted
    )

    # One rule, in the teal that means perception everywhere else in the UI.
    rule_y = text_y + 30 + 30
    draw.rectangle(
        [(OG_SIZE[0] // 2 - 44, rule_y), (OG_SIZE[0] // 2 + 44, rule_y + 2)],
        fill=(47, 163, 160),
    )
    return card


def main() -> int:
    lockup = dehalo(Image.open(LOCKUP_SOURCE))
    lockup.save(LOCKUP_OUT, "WEBP", quality=92, method=6, exact=True)
    print(f"{LOCKUP_OUT.name:18} {lockup.size[0]}x{lockup.size[1]}  "
          f"{LOCKUP_OUT.stat().st_size // 1024} KB "
          f"(from {LOCKUP_SOURCE.stat().st_size // 1024} KB)")

    spear = square(Image.open(SPEAR_SOURCE))
    spear.resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS).save(ICON_OUT, "PNG", optimize=True)
    spear.resize((APPLE_ICON_SIZE, APPLE_ICON_SIZE), Image.LANCZOS).save(
        APPLE_ICON_OUT, "PNG", optimize=True
    )
    print(f"{ICON_OUT.name:18} {ICON_SIZE}x{ICON_SIZE}")
    print(f"{APPLE_ICON_OUT.name:18} {APPLE_ICON_SIZE}x{APPLE_ICON_SIZE}")

    # Google Search reads a square favicon of at least 48px from a stable URL.
    # These are the sizes it and older browsers actually look for.
    spear.resize((48, 48), Image.LANCZOS).save(FAVICON_48, "PNG", optimize=True)
    spear.resize((96, 96), Image.LANCZOS).save(FAVICON_96, "PNG", optimize=True)
    spear.resize((256, 256), Image.LANCZOS).save(FAVICON_ICO, "ICO", sizes=ICO_SIZES)
    print(f"{FAVICON_48.name:18} 48x48")
    print(f"{FAVICON_96.name:18} 96x96")
    print(f"{FAVICON_ICO.name:18} {', '.join(f'{w}x{h}' for w, h in ICO_SIZES)}")

    card = social_card(lockup)
    card.save(OG_OUT, "PNG", optimize=True)
    print(f"{OG_OUT.name:18} {OG_SIZE[0]}x{OG_SIZE[1]}  {OG_OUT.stat().st_size // 1024} KB")

    # No favicon.svg. The artwork is raster, and wrapping a PNG in an <svg>
    # gives none of the reasons to prefer one — it does not scale, it is not
    # smaller, and it is not editable. A real one needs the vector redraw
    # docs/ROADMAP.md already records as owed.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
