"""Generate the milestone timeline from git (R107).

The timeline on `/impact` is read from `docs/milestones.json`, and this writes
it. Generated rather than maintained, for the reason the build panel's stack
list is (R57): a hand-written timeline is correct on the day it is typed and
slowly stops being, silently, because nothing checks it. This one cannot list a
milestone that did not land — every entry is a commit that exists, dated by the
commit.

A milestone is a commit whose subject carries a task id in brackets — `(R71)`,
`(R99, R100)`. That is already the convention in this repository, so the
timeline is a view of how the work was actually recorded rather than a second
place to record it.

Committed rather than read at request time: the Lambda has no repository.

    python scripts/milestones.py [--out docs/milestones.json]
"""

from __future__ import annotations

import argparse
import io
import json
import re
import subprocess
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout = io.TextIOWrapper(
        sys.stdout.buffer, encoding="utf-8", errors="replace", line_buffering=True
    )

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "milestones.json"

TASKS = re.compile(r"\(([RS]\d{1,3}(?:[a-z])?(?:\s*[,–—-]\s*[RS]?\d{1,3}[a-z]?)*)\)\s*$")
"""A task id, or a run of them, at the end of a commit subject."""

SEPARATOR = "\x1f"


def commits() -> list[dict[str, str]]:
    result = subprocess.run(
        ["git", "log", "--reverse", f"--format=%H{SEPARATOR}%aI{SEPARATOR}%s"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    out = []
    for line in result.stdout.splitlines():
        if line.count(SEPARATOR) != 2:
            continue
        sha, when, subject = line.split(SEPARATOR)
        out.append({"sha": sha, "at": when, "subject": subject})
    return out


def milestones() -> list[dict[str, str]]:
    found = []
    for commit in commits():
        match = TASKS.search(commit["subject"])
        if not match:
            continue
        subject = commit["subject"]
        # The subject without the trailing task ids and without the
        # Conventional Commits prefix: what the change actually was, which is
        # the only part a reader of a timeline wants.
        title = TASKS.sub("", subject).strip()
        title = re.sub(r"^[a-z]+(\([^)]*\))?:\s*", "", title).strip()
        found.append(
            {
                "tasks": [t.strip() for t in re.split(r"[,–—-]", match.group(1)) if t.strip()],
                "title": title,
                "at": commit["at"],
                "sha": commit["sha"][:7],
            }
        )
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(OUT))
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    found = milestones()
    payload = {
        "note": (
            "Generated by scripts/milestones.py from commit subjects carrying a "
            "task id. Do not edit by hand — a timeline nobody generates is one "
            "that silently stops matching the work."
        ),
        "count": len(found),
        "milestones": found,
    }
    rendered = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    out = Path(args.out)
    if args.check:
        # **Correctness, not exhaustiveness.** The file is committed *in* a
        # commit, so it can never contain that commit — a check demanding the
        # two be identical would fail immediately after every single commit and
        # would be switched off within a week. What must hold is that nothing
        # already in the file is wrong: it is a prefix of the current history,
        # in order, entry for entry. Anything newer is simply not in it yet, and
        # the count of those is printed rather than hidden.
        if not out.exists():
            print(f"FAIL  {out.relative_to(ROOT)} has not been generated")
            return 1
        try:
            committed = json.loads(out.read_text(encoding="utf-8")).get("milestones", [])
        except json.JSONDecodeError as error:
            print(f"FAIL  {out.relative_to(ROOT)} is not readable: {error}")
            return 1
        if committed != found[: len(committed)]:
            for index, (was, now) in enumerate(zip(committed, found)):
                if was != now:
                    print(f"FAIL  entry {index} disagrees with git: {was} / {now}")
                    return 1
            print(f"FAIL  {out.relative_to(ROOT)} has {len(committed)} entries, git has {len(found)}")
            return 1
        behind = len(found) - len(committed)
        print(
            f"{out.relative_to(ROOT)} matches git for all {len(committed)} entries"
            + (f"; {behind} newer commit(s) not in it yet" if behind else "")
        )
        return 0

    out.write_text(rendered, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} — {len(found)} milestones")
    for entry in found[-5:]:
        print(f"  {entry['at'][:10]}  {','.join(entry['tasks']):<12} {entry['title'][:60]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
