"""Generate the paper's results tables from the run records.

    python scripts/papertables.py > docs/research/tables.md

Nothing here is typed by hand. A results table transcribed into prose drifts
from the data the moment either changes, and the drift is invisible — the number
in the paper still looks like a number. Tables are regenerated from
`benchmark/results/` and the paper includes them.

An arm with no records is printed as a row saying so, rather than left out. A
four-column comparison with two columns silently missing reads as a two-arm
study that always intended to be one.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, "packages/core")

from pashupatastra.metrics import (  # noqa: E402
    NOT_COMPUTABLE,
    compute,
    load_records,
    per_scenario,
)

RESULTS = Path("benchmark/results")

# Every arm the paper claims to compare, whether or not it produced data.
ARMS = ("human", "runbook", "naive-llm", "pashupatastra")

ABSENT: dict[str, str] = {
    "human": (
        "not run — requires operators. A simulated human is the number this "
        "work would most like to see and the one nobody would check"
    ),
    "naive-llm": (
        "not run — requires a configured model. The deterministic stub would "
        "produce a second runbook under an LLM label"
    ),
}


def records_for(arm: str, suffix: str = "") -> list:
    path = RESULTS / arm / f"runs{suffix}.jsonl"
    return load_records(path) if path.exists() else []


def main() -> int:
    print("<!-- Generated by scripts/papertables.py. Do not edit by hand. -->\n")

    print("## Table 1 — Arms\n")
    print("Safety metric first. ARR is trivially maximised by acting recklessly,")
    print("so it is never printed above the rate of acting wrongly.\n")
    print("| Arm | FRR | HIR | ARR | VSR | Correct | n |")
    print("|-----|----:|----:|----:|----:|--------:|--:|")

    for arm in ARMS:
        records = records_for(arm)
        if not records:
            print(f"| {arm} | — | — | — | — | — | 0 |")
            continue
        m = compute(records)
        correct = round(m.correct / m.scoreable, 4) if m.scoreable else 0.0
        print(
            f"| {arm} | {m.frr:.4f} | {m.hir:.4f} | {m.arr:.4f} | "
            f"{m.vsr:.4f} | {correct:.4f} | {m.scoreable} |"
        )

    print("\n**Arms with no data, and why:**\n")
    for arm, reason in ABSENT.items():
        if not records_for(arm):
            print(f"- `{arm}` — {reason}")

    print("\n## Table 2 — Ablations\n")
    print("Only components the arm actually exercises can be ablated. Removing a")
    print("stage that never ran returns the baseline score and would be reported")
    print("as *no effect*, which reads as evidence the component does not matter.\n")
    print("| Variant | FRR | HIR | ARR | Correct | n |")
    print("|---------|----:|----:|----:|--------:|--:|")

    baseline = records_for("pashupatastra")
    if baseline:
        m = compute(baseline)
        correct = round(m.correct / m.scoreable, 4) if m.scoreable else 0.0
        print(f"| full architecture | {m.frr:.4f} | {m.hir:.4f} | {m.arr:.4f} "
              f"| {correct:.4f} | {m.scoreable} |")

    for ablation in ("no-policy", "no-verification"):
        records = records_for("pashupatastra", f"-{ablation}")
        if not records:
            print(f"| −{ablation} | — | — | — | — | 0 |")
            continue
        m = compute(records)
        correct = round(m.correct / m.scoreable, 4) if m.scoreable else 0.0
        print(f"| −{ablation} | {m.frr:.4f} | {m.hir:.4f} | {m.arr:.4f} "
              f"| {correct:.4f} | {m.scoreable} |")

    print("\n**Ablations that cannot be measured here:**\n")
    print("- `−hypothesis-evidence`, `−smriti`, `−adjacency` — all three sit in "
          "the reasoning path, which the benchmark arm never invokes")

    print("\n## Table 3 — Per-scenario results\n")
    print("Published rather than aggregated. A mean hides which cases fail, and")
    print("a scenario correct in some runs and not others is not a scenario that")
    print("works.\n")

    if baseline:
        print("| Scenario | Expected | Correct/runs | Verdicts |")
        print("|----------|----------|-------------:|----------|")
        for row in per_scenario(baseline):
            mark = " **UNSTABLE**" if row.unstable else ""
            verdicts = ", ".join(f"{k}×{v}" for k, v in row.verdicts.items())
            print(f"| {row.scenario_id} | {row.outcome} | {row.correct}/{row.runs} "
                  f"| {verdicts}{mark} |")
    else:
        print("_No records for the full architecture yet._")

    print("\n## Table 4 — Metrics not computed\n")
    print("Defined in METRICS.md and absent from the tables above. Listed so a")
    print("reader does not mistake five reported metrics for all of them.\n")
    print("| Metric | Why it is absent |")
    print("|--------|------------------|")
    for metric, reason in NOT_COMPUTABLE.items():
        print(f"| {metric} | {reason} |")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
